<?php

/**
 * This is the model base class for the table "{{tag}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TagModel".
 *
 * Columns in table "{{tag}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $frequency
 *
 */
abstract class BaseTagModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{tag}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TagModel|TagModels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('frequency', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>128),
			array('frequency', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, frequency', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'frequency' => Yii::t('app', 'Frequency'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('frequency', $this->frequency);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}