<?php

/**
 * This is the model base class for the table "{{user_web}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserWebModel".
 *
 * Columns in table "{{user_web}}" available as properties of the model,
 * followed by relations of table "{{user_web}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $profile
 *
 * @property Post[] $posts
 */
abstract class BaseUserWebModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{user_web}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserWebModel|UserWebModels', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, password, email', 'required'),
			array('username, password, email', 'length', 'max'=>128),
			array('profile', 'safe'),
			array('profile', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, username, password, email, profile', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'posts' => array(self::HAS_MANY, 'Post', 'author_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'email' => Yii::t('app', 'Email'),
			'profile' => Yii::t('app', 'Profile'),
			'posts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('profile', $this->profile, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}